package com.webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IQueryMapServer", targetNamespace = "http://impl.queryMap.cxf.control.ws.com/")
public interface IQueryMapServer {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sendAlert", targetNamespace = "http://impl.queryMap.cxf.control.ws.com/", className = "com.webService.SendAlert")
	@ResponseWrapper(localName = "sendAlertResponse", targetNamespace = "http://impl.queryMap.cxf.control.ws.com/", className = "com.webService.SendAlertResponse")
	public String sendAlert(@WebParam(name = "arg0", targetNamespace = "")
	String arg0, @WebParam(name = "arg1", targetNamespace = "")
	String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sendTest", targetNamespace = "http://impl.queryMap.cxf.control.ws.com/", className = "com.webService.SendTest")
	@ResponseWrapper(localName = "sendTestResponse", targetNamespace = "http://impl.queryMap.cxf.control.ws.com/", className = "com.webService.SendTestResponse")
	public String sendTest(@WebParam(name = "arg0", targetNamespace = "")
	QueryMapEntity arg0);

}
