theembers:
  iot.netty.port: 12345

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer.group-id: 0
    producer:
      batch-size: 65536
      buffer-memory: 524288
  redis:
    database: 10
    host: localhost
    port: 6379
    timeout: 3000
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
    host: localhost

loggingpath: ./logs